### PR TITLE
Fix the wonk present in the JSON styling.

### PR DESCRIPTION
**Pull request by betawaffle**
I don't know how to test this to make sure it looks right yet.

### CODE REVIEW

**Comment by jacobsmith928** [comment]
@jake anything we need to do here?  @ronggur @AriaEdo can you coordinate anything on your end so we can display correctly on the site?


https://www.packet.net/resources/docs/#page:devices,header:devices-project
(click on one of the show buttons)

**Comment by theunraveler** [comment]
This PR has been merged already. Has the work been deployed yet (the API docs rebuilt)?

**Comment by jacobsmith928** [comment]
not sure, @ronggur can you confirm?

**Comment by ronggur** [comment]
We're sorry, It's css issue. I've updated the style

**Comment by betawaffle** [comment]
It's good now in production, thanks!

**Pull request merged**
